### ISSUE TITLE
First key after pressing ESC still uppercase

### ISSUE THREAD

**Issue by jsenin** [suxpert/vimcaps#4]
Hi !

Thanks for your work with this plugin, it's very useful.
I would like to collaborate improving this case:
- enter insert mode
- press capslock
- write something ej. AAAAAAAAAA
- press ESC
- press k ( for moving up one line )
- status message shows: `E349: No identifier under the cursor`.
- next pressed keys are lowercase

So the first after press ESC still uppercase.
How can I fix it ? 
thanks

--
Running:
- Debian 9 
- vim 2:8.0.0197-4+deb9u1

**Comment by suxpert** [comment]
Since it has been to long without further feedback, I'll close this issue.

If there are still any problems, feel free to re-open it.
