### ISSUE TITLE
"Library Error. vimcaps can not load!" on Win10 64bit

### ISSUE THREAD

**Issue by harupiyo** [suxpert/vimcaps#6]
Hi LiTuX
Thanks for the script, which is exactly indispensable when using CapsLock!

I installed it on Windows 10 and got the following error
![](https://gyazo.com/71123abd141611700bd77fa6d8a30aac.png)

The :version in Vim is as follows.
![](https://gyazo.com/44eb2d3102c57eab8d3f09c79c756287.png)

I followed the execution of the script and found that it threw an exception on this line.

https://github.com/suxpert/vimcaps/blob/master/autoload/vimcaps.vim#L54

Unfortunately, not being familiar with libcallnr, I was unable to track it down any further.

Please let me know if there is anything I can do to help solve this problem.

thanks.

**Comment by suxpert** [comment]
Hi harupiyo,

I've done some quick test on Windows 10 Home x64 21H2 with the [official](https://www.vim.org/download.php#pc) 32 bit gvim 8.2 and gvim 9.0, everything works as expected. So I guess it might be an issue of 64 bit version.

I'll dig more on the [nightly build version](https://github.com/vim/vim-win32-installer) later this day. And BTW, which build do you use? Would you mind sending me a copy (or link) so I can also test on it?

Happy vimming. :)

**Comment by harupiyo** [comment]
Hi LiTuX!
Thanks for your reply.

You are right, that was exactly the problem that happens with the 64-bit version of Vim.
The 32bit binary of Vim did not have the problem.
I have also confirmed that the problem reproduces itself in the 64-bit version.

I am using gvim.exe, which is a major binary in Japan and is distributed here
https://www.kaoriya.net/software/vim/

Links to the 32-bit and 64-bit versions are provided below.　
- 32bit(OK) :: http://vim-jp.org/redirects/koron/vim-kaoriya/latest/win32/
- 64bit(NG) :: http://vim-jp.org/redirects/koron/vim-kaoriya/latest/win64/

We have also confirmed that the same results are obtained with the official binaries distributed at vim.org.

- 32bit(OK) :: https://github.com/vim/vim-win32-installer/releases/download/v9.0.0089/gvim_9.0.0089_x86.zip
- 64bit(NG) :: https://github.com/vim/vim-win32-installer/releases/download/v9.0.0089/gvim_9.0.0089_x64.zip

Please let us know if i can be of any help.
Thank you!

**Comment by suxpert** [comment]
Hi harupiyo,

Sorry for the lated response. According to my test, this issue should be fixed, please confirm.

Happy vimming. :)

**Comment by harupiyo** [comment]
Hi!

Confirmed.
We no longer have this problem.

Thank you from the bottom of my heart.
